"""create comments table, add to to_dicts()

Revision ID: d2679450ce54
Revises: 716a6208da9b
Create Date: 2021-04-01 15:21:35.857974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2679450ce54'
down_revision = '716a6208da9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    comment_table = op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(comment_table, [{"task_id" : "1", "text" : "There is so much mail! It will be great!"}])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
